#include <stdio.h>
#include <stdlib.h>

// This is the magic header file generated by our Python script.
// It contains the actual data we're going to print.
#include "riscv_inst.h"

/**
 * A simple helper to print a string for our YAML output.
 * To keep things simple and safe, we'll just wrap every string in double quotes.
 * This isn't a full-blown YAML library, but it's good enough for this job.
 */
void print_yaml_string(const char* s) {
    // Make sure we don't crash on a null string.
    if (s) {
        printf("\"%s\"", s);
    } else {
        printf("\"\"");
    }
}

int main() {
    // The riscv_instructions array and its size are defined for us
    // inside "riscv_inst.h". All we have to do is loop through it.

    // A valid YAML file often starts with this.
    printf("---\n");

    // Loop over each instruction in the array.
    for (int i = 0; i < riscv_instruction_count; i++) {
        const RiscVInstruction* inst = &riscv_instructions[i];

        // In YAML, a hyphen starts a new item in a list.
        printf("- name: ");
        print_yaml_string(inst->name);
        printf("\n");

        // The other properties are indented to show they belong to this item.
        printf("  isa: ");
        print_yaml_string(inst->isa);
        printf("\n");

        printf("  description: ");
        print_yaml_string(inst->description);
        printf("\n");

        printf("  encoding: ");
        print_yaml_string(inst->encoding);
        printf("\n");

        printf("  extension: ");
        print_yaml_string(inst->extension);
        printf("\n");
    }

    return 0; // All done!
}
